version: '3.8'

services:

  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgis_container
    environment:
      POSTGRES_DB: osm_switzerland
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: your.email@mail.com
      PGADMIN_DEFAULT_PASSWORD: your_pgadmin_password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - db

volumes:
  db_data:
  pgadmin_data:
